In [0]:
!pip install -U -q PyDrive
!pip install torch==0.4.0
!pip install spacy
!python -m spacy download en_core_web_md
!pip install numpy

#now imports
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

import torch
import torch.nn as nn
import spacy
import numpy as np
import json
from google.colab import files

In [0]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [0]:
#1WYT_IUd0eZLiL45qGIIS78iLwh-laVgx
file_id = '1WYT_IUd0eZLiL45qGIIS78iLwh-laVgx'
downloaded = drive.CreateFile({'id': file_id})
downloaded.GetContentFile('test.json')

In [15]:
import numpy as np
import torch
import spacy
from torch.utils.data import Dataset, DataLoader
import json


class myDataset(Dataset):
	def __init__(self,filename,y=0):
		self.nlp=spacy.load("en_core_web_md")
		self.filename=filename
		self.length=0
		with open(filename) as fp:
			s=fp.read()
		self.arr=s.split('\n')
		self.y=y


	def __len__(self):
		if self.length == 0:
			for i in range(len(self.arr)-1):
				try:
					obj=json.loads(self.arr[i])
					self.length+=len(obj["sentences"])
				except ValueError:
					print('got a Value error(most probably improper JSON at '+str(i))
					pass
		return self.length
	
	def __getitem__(self,idx):
		index=0
		for i in range(len(self.arr)):
			obj=json.loads(self.arr[i])
			no_of_ans=len(obj["sentences"])
			if((index+no_of_ans)>idx) :
				break
			index+=no_of_ans
		print(i)
		if self.y :
			if (idx-index) in obj["candidates"]:
				return 1
			else:
				return 0
		question=self.nlp(obj["question"])
		answer=self.nlp(obj["sentences"][idx-index])
		list_of_tokens=[]
		for i in range(40):
			if(i<len(question)):
				list_of_tokens.append(torch.Tensor(question[i].vector).cuda(0))
			else:
				list_of_tokens.append(torch.zeros(300).cuda(0))
		for i in range(40):
			if(i<len(answer)):
    				list_of_tokens.append(torch.Tensor(answer[i].vector).cuda(0))
			else:
				list_of_tokens.append(torch.zeros(300).cuda(0))
		sentence_to_embedding=torch.stack(list_of_tokens,dim=0)
		return sentence_to_embedding
		
		

d=myDataset('test.json',y=0)
# print(len(d))
# print(len(d))
# print(len(d))
# print(len(d))
# print(len(d))
# print(len(d))
# print(d[50000])
# print(d[2000])
# print(d[20500])
# print(d[52000].shape)
for i in range(200):
  print(i)
  print(d[i])

0
0
tensor([[-0.1356,  0.3322, -0.3602,  ..., -0.1730,  0.2168,  0.2221],
        [ 0.0438,  0.0248, -0.2094,  ..., -0.3010, -0.1458,  0.2819],
        [ 0.1275,  0.8323,  0.4600,  ..., -0.0233, -0.1721, -0.5072],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]], device='cuda:0')
1
0
tensor([[-0.1356,  0.3322, -0.3602,  ..., -0.1730,  0.2168,  0.2221],
        [ 0.0438,  0.0248, -0.2094,  ..., -0.3010, -0.1458,  0.2819],
        [ 0.1275,  0.8323,  0.4600,  ..., -0.0233, -0.1721, -0.5072],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]], device='cuda:0')
2
0
tensor([[-0.1356,  0.3322, -0.3602,  ..., -0.1730,  0.2168,  0.2221],
        [ 0.0438

tensor([[ 0.0892,  0.2579,  0.2628,  ...,  0.1442, -0.1690,  0.2650],
        [-0.0385,  0.5425, -0.2184,  ...,  0.1180,  0.2459,  0.2287],
        [-0.1101,  0.1970,  0.1771,  ...,  0.1669,  0.1457, -0.3501],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]], device='cuda:0')
41
2
tensor([[ 0.0892,  0.2579,  0.2628,  ...,  0.1442, -0.1690,  0.2650],
        [-0.0385,  0.5425, -0.2184,  ...,  0.1180,  0.2459,  0.2287],
        [-0.1101,  0.1970,  0.1771,  ...,  0.1669,  0.1457, -0.3501],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]], device='cuda:0')
42
2
tensor([[ 0.0892,  0.2579,  0.2628,  ...,  0.1442, -0.1690,  0.2650],
        [-0.0385, 

tensor([[ 0.0746,  0.2693, -0.0277,  ...,  0.0806,  0.3729, -0.3212],
        [-0.0689,  0.3877, -0.2612,  ...,  0.1930,  0.3753,  0.1458],
        [-0.6869,  0.5252,  0.1187,  ..., -0.4946, -0.4796,  0.3016],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]], device='cuda:0')
77
4
tensor([[ 0.0746,  0.2693, -0.0277,  ...,  0.0806,  0.3729, -0.3212],
        [-0.0689,  0.3877, -0.2612,  ...,  0.1930,  0.3753,  0.1458],
        [-0.6869,  0.5252,  0.1187,  ..., -0.4946, -0.4796,  0.3016],
        ...,
        [-0.5428,  0.5784,  0.1455,  ..., -0.3362, -0.8018, -0.0259],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.0828,  0.6720, -0.1499,  ..., -0.1918, -0.3785, -0.0659]], device='cuda:0')
78
4
tensor([[ 0.0746,  0.2693, -0.0277,  ...,  0.0806,  0.3729, -0.3212],
        [-0.0689, 

tensor([[ 0.0746,  0.2693, -0.0277,  ...,  0.0806,  0.3729, -0.3212],
        [ 0.2900, -0.2296, -0.4198,  ...,  0.0343,  0.2043,  0.4815],
        [-0.0752,  0.5734, -0.3191,  ...,  0.3280, -0.1093, -0.3795],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]], device='cuda:0')
116
7
tensor([[ 0.0746,  0.2693, -0.0277,  ...,  0.0806,  0.3729, -0.3212],
        [ 0.2900, -0.2296, -0.4198,  ...,  0.0343,  0.2043,  0.4815],
        [-0.0752,  0.5734, -0.3191,  ...,  0.3280, -0.1093, -0.3795],
        ...,
        [-0.0702,  0.1527, -0.3309,  ..., -0.1373,  0.1575,  0.6155],
        [-0.0876,  0.3550,  0.0639,  ...,  0.0345, -0.1503,  0.4067],
        [ 0.0120,  0.2075, -0.1258,  ...,  0.1387, -0.3605, -0.0350]], device='cuda:0')
117
7
tensor([[ 0.0746,  0.2693, -0.0277,  ...,  0.0806,  0.3729, -0.3212],
        [ 0.2900

tensor([[-0.0385,  0.5425, -0.2184,  ...,  0.1180,  0.2459,  0.2287],
        [-0.0850,  0.5020,  0.0024,  ..., -0.2151, -0.2630, -0.0060],
        [ 0.2720, -0.0620, -0.1884,  ...,  0.1302, -0.1832,  0.1323],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]], device='cuda:0')
152
10
tensor([[-0.0385,  0.5425, -0.2184,  ...,  0.1180,  0.2459,  0.2287],
        [-0.0850,  0.5020,  0.0024,  ..., -0.2151, -0.2630, -0.0060],
        [ 0.2720, -0.0620, -0.1884,  ...,  0.1302, -0.1832,  0.1323],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]], device='cuda:0')
153
10
tensor([[-0.0385,  0.5425, -0.2184,  ...,  0.1180,  0.2459,  0.2287],
        [-0.08

tensor([[ 0.2050,  0.3006, -0.3026,  ...,  0.1146,  0.2624,  0.0222],
        [-0.0689,  0.3877, -0.2612,  ...,  0.1930,  0.3753,  0.1458],
        [ 0.2720, -0.0620, -0.1884,  ...,  0.1302, -0.1832,  0.1323],
        ...,
        [ 0.3587,  0.0332, -0.1286,  ...,  0.2382,  0.2369,  0.0828],
        [ 0.2595, -0.1629,  0.4789,  ...,  0.0337, -0.0070, -0.0944],
        [ 0.0602,  0.2180, -0.0425,  ...,  0.1171, -0.1669, -0.0941]], device='cuda:0')
188
12
tensor([[ 0.2050,  0.3006, -0.3026,  ...,  0.1146,  0.2624,  0.0222],
        [-0.0689,  0.3877, -0.2612,  ...,  0.1930,  0.3753,  0.1458],
        [ 0.2720, -0.0620, -0.1884,  ...,  0.1302, -0.1832,  0.1323],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]], device='cuda:0')
189
12
tensor([[ 0.2050,  0.3006, -0.3026,  ...,  0.1146,  0.2624,  0.0222],
        [-0.06